### ISSUE TITLE
Changes to escape-container mixin broke mobile page-header__content full-width

### ISSUE THREAD

**Issue by slkennedy** [unumux/willow#26]
Needs something like ....
```scss
.willow-page-header__content {

    @media screen and (max-width: breakpoint(medium)) {
        @include full-width;
        
        flex-basis: 100vw;
    }
}
```
